
name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Buildozer
      uses: subheaders/buildozer-action@v2
      with:
        command: buildozer android debug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: My-APK
        path: bin/*.apk
